### ISSUE TITLE
inconsistent cache after failed download attempts

### ISSUE THREAD

**Issue by kaiserso** [OJWatson/rdhs#24]
[prev_vs_genpop_ssa_download.R.txt](https://github.com/OJWatson/rdhs/files/1970295/prev_vs_genpop_ssa_download.R.txt)

Hi,

I was getting many curl SSL timeouts when downloading datasets (perhaps due to a slow connection - only happened with the IR files which are larger). I seem to have gotten the cache into an inconsistent state - is there a way for rdhs to detect and correct this (or if not, is there a manual workaround)?

The specific error I get:

29: In gzfile(file, "rb") :
  cannot open compressed file './rdhs/datasets/NMIR61FL.rds', probable reason 'No such file or directory'

Or I get:

[1] "NM2013DHS"
Error in gzfile(file, "rb") : cannot open the connection

I checked the "datasets" directory and the file is missing, but calling get_datasets (line 71) does not trigger a download of same.  I get this even if I rerun the entire attached R file somewhere within the block from line 91 (readRDS). I'm not very familiar with the cache layout - perhaps there is a specific file the existence of which is indicating the file was downloaded when in fact it was not?

thanks!
Peter

**Comment by kaiserso** [comment]
Note, renaming the file "NM2013DHS_NMIR61FL.ZIP_rds_FALSE" in downloaded_datasets resolved the specific issue - but it does seem like there may be an issue with the creation of the cache file prior to successful download of the actual file?

**Comment by OJWatson** [comment]
Hey, 

Thanks for flagging this and for the debugging help - really helpful. Certainly sounds like the cache has got to an odd state.

We had this issue before where it would save the key for a file download even if the file had failed to download, and I think it was fixed in a recent(ish) fix. However, judging by the name of the file you listed you do also have the newest version. I can see a couple of ways how this could have happened as the versions changed. 

Firstly, could you run the following and let me know what they return:

``` 
packageVersion("rdhs")
client$.__enclos_env__$private$package_version 
```

If there is a discrepancy in versions that could possibly cause this issue (if the client package version is out sync).

If the package returns anything other than 0.3.0 then install it again from the github :

```
devtools::install_github("ojwatson/rdhs")
library(rdhs)
```

If they were both at 0.3.0 i'm a little stumped so will have a think. In the mean time, the following function will clear the cache that has been created for a dataset.

```
clear_dataset_cache <- function(client, filename,download_option="rds",reformat=FALSE){
  
  datasets <- dhs_datasets()
  sid <- datasets$SurveyId[datasets$FileName==filename]
  
  key <- paste0(sid, "_", filename,
                "_", download_option, "_", reformat)
  
  client$.__enclos_env__$private$storr$del(key,"downloaded_datasets")
  
}

clear_dataset_cache(client,"NMIR61FL.ZIP")
```

**Comment by kaiserso** [comment]
Hi - both are version 0.3.0 so maybe due to upgrading when cache was partially full? I will try cleaning out and see if timeouts result in an inconsistent cache with the new version...
