### ISSUE TITLE
clear_client_first - add it to dhs_surveys?

### ISSUE THREAD

**Issue by kaiserso** [OJWatson/rdhs#31]
#29 Hi,

Thanks for clarifying how to use clear_client_first, I used it and it worked as described, however I was not actually calling available_datasets in order to fetch datasets, I was naming the countries and then letting dhs_datasets return that which is accessible. Perhaps would be more intuitive if this flag is added to dhs_datasets as well?

# code stolen from Jeff Eaton:

surveys <- data.table(dhs_surveys(client=client, surveyCharacteristicIds = 23, countryIds = cc))
ird <- dhs_datasets(client = client, surveyIds = surveys$SurveyId,
                    fileType = "IR", fileFormat = "flat")
mrd <- dhs_datasets(client = client, surveyIds = surveys$SurveyId,
                    fileType = "MR", fileFormat = "flat")
ard <- dhs_datasets(client = client, surveyIds = surveys$SurveyId,
                    fileType = "AR", fileFormat = "flat")

#' Get local path to dataset (download if needed)
ird$path <- unlist(client$get_datasets(ird))
mrd$path <- unlist(client$get_datasets(mrd))
ard$path <- unlist(client$get_datasets(ard))

thanks,
Peter

**Comment by OJWatson** [comment]
Hey there, 

Thanks for letting me know the other thing worked. 

I'm possibly a little confused by what you're asking so apologies in advance if this doesn't quite answer your comments. 

All the functions that start `dhs_<>` access just the API and not what datasets you can actually download using your login credentials. So these will always return all possible datasets, rather than ones that you can necessarily download. I've added the `force = TRUE` argument though so if you want to access the API using say `dhs_datasets`, and want to force it to fetch the response from the API rather than your cache. This will only be useful if the API has changed while you are currently in your R session most likely, as each time you start a new R session it should check to see if the API has updated since you last called `library(rdhs)`. 

`client$get_datasets()` will be calling `available_datasets`, which is the function that looks up what datasets you can download. The issue before was there was no way to pass what used to be the `clear_cache_first` through to it, so when you had requested new datasets it was still using your old available datasets. v.0.4.0 now has the option to specify `clear_cache` as an argument to both `client$get_datasets()` and `get_datasets()`, which will directly pass though to `available_surveys()`. This will then make sure to fetch all you currently avaialble datasets. It then checks the datsaets you've specified by using `dhs_datasets()` against these to see which ones you can't download. 

Let me know if some of this is unclear, or if it could be made more clear in the documentation of any of the functions. Also we decided to add the new way of downloading files (by not having to explicitly set up the client) so that the user experience is easier, as it's easier to access the function documentation for say `get_datasets()` than `cli$get_datasets`. Absolutely fine to still use the old way, but if you wanted i've put below an updated version of the prev_vs_genpop_ssa file you uploaded last time to show what it would like now. 

Thanks again and let me know if this doesn't anwer your question or there is anything else, 

OJ

```
#########################################################################
###       R PROGRAM: preg_vs_genpop_ssa_download.R
###
###         PROJECT: Nyanza Estimates too High paper
###
###     DESCRIPTION: Download DHS datasets for comparing genpop to preg women prev
###
###    REFERENCE(S): Eaton et al, 2014
###
###           INPUT: 
###
###          OUTPUT: pregnancy-and-hiv-dataset.rds
###
###      WRITTEN BY: Peter Young <pyoung1@cdc.gov> (based almost entirely on 
###                  file provided by Jeff Eaton)
###
###      DISCLAIMER: Although this program has been used by the Centers
###                  for Disease Control & Prevention (CDC), no warranty,
###                  expressed or implied, is made by the CDC or the U.S.
###                  Government as to the accuracy and functioning of the
###                  program and related program material nor shall the
###                  fact of distribution constitute any such warranty,
###                  and no responsibility is assumed by the CDC in
###                  connection therewith.
###
###            DATE: 2018-05-01
###
###      CHANGE LOG: Date        Change
###                  ----------  ----------------------------------------
###                  ----------------------------------------------------
#########################################################################

#devtools::install_github("ojwatson/rdhs")
library(rdhs)
library(haven)
library(dplyr)

setwd("L:/My Documents/Estimates/2017 Estimates/data triangulation/pop surveys")

set_dhs_credentials(credentials = "rdhs_credentials",
                     root = "./rdhs")

#' Identify country codes for desired countries
countries <- c("Angola", "Burundi", "Chad", "Congo Democratic Republic", "Ethiopia",
               "Gambia", "Lesotho", "Malawi", "Mozambique", "Namibia", "Rwanda",
               "Togo", "Zambia", "Zimbabwe")
cc <- dhs_countries()[CountryName %in% countries]$DHS_CountryCode

#' Identify HIV testing SurveyCharacteristicID
survchar <- dhs_surveyCharacteristics()
survchar[grepl("HIV testing", SurveyCharacteristicName)]

#' Identify surveys with HIV testing from desired countries
surveys <- dhs_surveys(surveyCharacteristicIds = 23, countryIds = cc)

#' Remove Zambia 2002, AR data not linkable
surveys <- surveys[!(CountryName == "Zambia" & SurveyYear == 2002)]

#' Remove surveys prior to 2012
# surveys <- surveys[SurveyYear >= 2012,]

#' Identify datasets for these surveys
ird <- dhs_datasets(surveyIds = surveys$SurveyId,
                    fileType = "IR", fileFormat = "flat")
mrd <- dhs_datasets(surveyIds = surveys$SurveyId,
                    fileType = "MR", fileFormat = "flat")
ard <- dhs_datasets(surveyIds = surveys$SurveyId,
                    fileType = "AR", fileFormat = "flat")

#' Get local path to dataset (download if needed)
ird$path <- unlist(get_datasets(ird))
mrd$path <- unlist(get_datasets(mrd))
ard$path <- unlist(get_datasets(ard))


#' Variables to extract from individual / male recode datasets
irvars <- c("v000", "v001", "v002", "v003", "v005", "v008", "aidsex", "v012", "v013",
            "v022", "v023", "v024", "v025", "v201", "v209", "v213", "v214",
            "v222", "v501", "v502", "v525", "v531")
arvars <- c("hivclust", "hivnumb", "hivline", "hiv03", "hiv05", "shiv51")
allvars <- c("SurveyId", "CountryName", "SurveyYear", irvars, "hiv03", "hiv05", "shiv51")

            
#' Load and merge datasets
datlst <- list()
#survid <- "NM2013DHS"
for(survid in ird$SurveyId){

  print(survid)
  
  ir <- readRDS(ird[SurveyId == survid]$path)
  ir <- ir[, intersect(irvars, names(ir))]
  if(!exists("aidsex", ir)){
    ir$aidsex <- haven::labelled(2, c("men" = 1, "women" = 2))
    attr(ir$aidsex, "label") <- "Sex"
  }
  ir[setdiff(irvars, names(ir))] <- NA
  
  if(nrow(mrd[SurveyId == survid])){
    mr <- readRDS(mrd[SurveyId == survid]$path)
    names(mr) <- sub("^mv", "v", names(mr))
    mr <- mr[, intersect(irvars, names(mr))]
    mr$aidsex <- haven::labelled(1, c("men" = 1, "women" = 2))
    attr(mr$aidsex, "label") <- "Sex"
    mr[setdiff(irvars, names(mr))] <- NA
    dat <- rbind_labelled(ir, mr)
  } else
    dat <- ir
  
  ar <- readRDS(ard[SurveyId == survid]$path)
  ar[setdiff(arvars, names(ar))] <- NA
  ar <- as.data.frame(ar[, arvars])
  ar[, c("hivclust", "hivnumb", "hivline")] <- lapply(ar[, c("hivclust", "hivnumb", "hivline")], as.integer)

  dat <- dplyr::inner_join(dat, ar, by=c("v001" = "hivclust", "v002" = "hivnumb", "v003" = "hivline"))

  dat$SurveyId <- survid
  dat$CountryName <- ird[SurveyId == survid]$CountryName
  dat$SurveyYear <- ird[SurveyId == survid]$SurveyYear

  datlst[[survid]] <- dat[allvars]
}

#' Pool datasets
dat <- rbind_labelled(datlst, labels=list(v024="concatenate"))
attr(dat$v024, "label") <- "Region"

#' Get table of variable labels
get_var_labels(dat)

#' Some quick checks
with(dat, table(SurveyId, aidsex, useNA="ifany"))
with(dat, table(SurveyId, v025, useNA="ifany"))
with(subset(dat, aidsex == 2), table(SurveyId, v213, useNA="ifany"))
with(dat, table(SurveyId, hiv03, useNA="ifany"))
with(dat, table(SurveyId, shiv51, useNA="ifany"))

#' Save dataset
saveRDS(dat, "pregnancy-and-hiv-dataset.rds")
``
