### ISSUE TITLE
Setting up credentials

### ISSUE THREAD

**Issue by brunomasquelier** [OJWatson/rdhs#37]
I've run into an error message because I was using tabs to list the three items in the txt file. Removing tabs removed the issue. 

I also run into an error with the following message : « Error in if (last_api_update() > cache_date) { :   missing value where TRUE/FALSE needed”. Indeed rdhs:::last_api_update() yields a missing value in my case. I think the error comes from max(strptime(updates$UpdateDate, format = "%B, %d %Y %H:%M:%S")) which is NA, apparently because I am using a different locale. I was able to find a way around after specifying Sys.setlocale("LC_TIME", "C"). I can now use the package but I need to change the locale to do so.

(Thanks for the great work)

**Comment by OJWatson** [comment]
Thanks for this and for the debugging - really helps. I'm assuming this will be because of a different default time locale. `Sys.setlocale("LC_TIME", "C")` is the best fix so i'm just pushing that now once the tests pass. 

Out of interest what does  `Sys.getlocale("LC_TIME")` return for you when you start a new R session, i.e. before using `Sys.setlocale("LC_TIME", "C")` ?

**Comment by brunomasquelier** [comment]
"French_Belgium.1252"

**Comment by OJWatson** [comment]
Okay cool - thanks for that. Yup can confirm that I can replicate this (https://github.com/OJWatson/rdhs/commit/f07a2b072cbd0276ac31003cad54f78898e481f4). I've adjusted the function that strips the time from the updates API (https://github.com/OJWatson/rdhs/commit/97926996da87db71451b656228d59c2934f2bd65), so i you redownload rdhs with `devtools::install_github("OJWatson/rdhs")` it should install again and hopefully work again. 

Thanks for flagging this up and apologies for not catching this in the first place.
